services:
  - type: web
    name: hepatitis-model
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
